In [1]:
import pandas as pd
import numpy as np

# Make prediction of wins based on hero decisions

In [2]:
# this is meant to be a simple example so only matches and players are used
matches = pd.read_csv('./data/match.csv', index_col=0)
players = pd.read_csv('./data/players.csv')

test_labels = pd.read_csv('./data/test_labels.csv', index_col=0)
test_players = pd.read_csv('data/test_player.csv')

train_labels = matches['radiant_win'].astype(int)

In [3]:
!ls data

ability_upgrades.csv   match_outcomes.csv     teamfights.csv
chat.csv               objectives.csv         teamfights_players.csv
cluster_regions.csv    player_ratings.csv     test_labels.csv
hero_names.csv         player_time.csv        test_player.csv
item_ids.csv           players.csv
match.csv              purchase_log.csv

# Data description

match.csv: match_id and radiant_win 

players.csv: match_id, hero_id, player_slot(0-4 is radiant, 128-132 is dire)

test_labels: radiant_wins for match_ids

test_players: Match_id, hero_id

goal:
from team composition, decide if radiant team won or lost

In [26]:
matches

,start_time,duration,tower_status_radiant,tower_status_dire,barracks_status_dire,barracks_status_radiant,first_blood_time,game_mode,radiant_win,negative_votes,positive_votes,cluster
match_id,,,,,,,,,,,,
0,1446750112,2375,1982,4,3,63,1,22,True,0,1,155
1,1446753078,2582,0,1846,63,0,221,22,False,0,2,154
2,1446764586,2716,256,1972,63,48,190,22,False,0,0,132
3,1446765723,3085,4,1924,51,3,40,22,False,0,0,191
4,1446796385,1887,2047,0,0,63,58,22,True,0,0,156
5,1446798766,1574,2047,4,3,63,113,22,True,0,0,155
6,1446800938,2124,1972,0,3,63,4,22,True,0,0,151
7,1446804030,2328,2046,0,0,63,255,22,True,0,0,138
8,1446819063,2002,0,1982,63,0,4,22,False,0,0,182
9,1446837251,2961,0,1972,63,0,85,22,False,0,0,133
10,1446839926,1562,1983,262,51,63,143,22,True,0,0,133
11,1446850598,3280,0,1974,63,0,76,22,False,0,0,122
12,1446853394,3995,0,1796,59,0,3,22,False,0,0,138
13,1446855028,2452,1956,6,3,63,120,22,True,0,0,123
14,1446855096,1728,2047,256,48,63,27,22,True,0,0,182
15,1446858132,3122,0,1540,19,0,101,22,False,0,0,121
16,1446860653,3318,0,1312,60,0,252,22,False,0,0,121
17,1446861016,3798,1543,0,0,3,4,22,True,0,2,123
18,1446862325,2820,4,1572,63,3,168,22,False,0,1,133
19,1446870404,2234,1974,0,0,63,112,22,True,0,0,184
20,1446874022,2284,1974,0,0,63,208,22,True,0,0,112
21,1446876812,2019,1974,0,2,63,49,22,True,0,0,111
22,1446887066,2754,1852,256,48,63,4,22,True,0,0,191
23,1446890850,2742,1958,0,0,63,4,22,True,0,0,132
24,1446892093,2986,0,1956,63,0,79,22,False,0,0,132
25,1446893288,2430,1974,0,0,63,5,22,True,0,0,153
26,1446894280,1499,2046,0,0,63,108,22,True,0,0,191
27,1446896551,2116,0,1846,63,0,111,22,False,0,0,192
28,1446899255,2201,2047,0,0,63,9,22,True,0,0,138
29,1446910512,3388,4,1796,63,51,80,22,False,0,0,155
...,...,...,...,...,...,...,...,...,...,...,...,...
49970,1447828823,3013,1588,0,48,15,98,22,True,0,0,121
49971,1447828834,1356,1983,256,48,63,9,22,True,0,0,123
49972,1447828842,2988,1796,0,32,63,173,22,True,0,0,123
49973,1447828839,2371,1828,0,0,63,3,22,True,0,0,151
49974,1447828847,2937,260,1798,63,51,363,22,False,0,0,152
49975,1447828854,2153,0,2047,63,0,6,22,False,0,0,171
49976,1447828908,1433,6,2047,63,3,104,22,False,0,0,132
49977,1447828968,2542,1982,0,0,63,117,22,True,0,0,154
49978,1447828970,2391,2046,0,0,63,89,22,True,0,0,123
49979,1447829031,2298,390,1846,63,51,204,22,False,0,0,153
49980,1447829030,1374,2047,0,0,63,85,22,True,0,0,122
49981,1447829049,4558,0,1830,63,0,151,22,False,0,0,204
49982,1447829043,3099,0,1846,63,0,8,22,False,0,0,112
49983,1447829039,1831,1982,384,48,63,0,22,True,0,0,121
49984,1447829056,2051,1982,256,48,63,15,22,True,0,0,121
49985,1447829075,1942,0,2044,63,0,3,22,False,0,0,156
49986,1447829058,2917,1972,0,16,63,71,22,True,0,0,138
49987,1447829087,3130,1975,0,0,63,6,22,True,0,0,123
49988,1447829126,2124,4,1972,63,3,142,22,False,0,0,191
49989,1447829126,1556,4,2046,63,3,223,22,False,0,0,121
49990,1447829137,3580,1972,0,0,63,5,22,True,0,0,111
49991,1447829136,2883,1828,0,0,63,62,22,True,0,0,123
49992,1447829133,3159,384,1796,63,48,6,22,False,0,0,156
49993,1447829156,2410,0,1982,63,0,0,22,False,0,0,154
49994,1447829171,2620,0,1846,63,0,215,22,False,0,0,155
49995,1447829192,3025,1824,0,0,63,117,22,True,0,0,111
49996,1447829181,1451,1982,384,48,63,147,22,True,0,0,204
49997,1447829197,2672,1830,0,0,63,130,22,True,0,0,111
49998,1447829189,2211,1982,4,3,63,645,22,True,0,0,151
49999,1447829215,2788,0,2046,63,0,326,22,False,0,0,154

In [32]:
matches.reset_index()

,match_id,start_time,duration,tower_status_radiant,tower_status_dire,barracks_status_dire,barracks_status_radiant,first_blood_time,game_mode,radiant_win,negative_votes,positive_votes,cluster
0,0,1446750112,2375,1982,4,3,63,1,22,True,0,1,155
1,1,1446753078,2582,0,1846,63,0,221,22,False,0,2,154
2,2,1446764586,2716,256,1972,63,48,190,22,False,0,0,132
3,3,1446765723,3085,4,1924,51,3,40,22,False,0,0,191
4,4,1446796385,1887,2047,0,0,63,58,22,True,0,0,156
5,5,1446798766,1574,2047,4,3,63,113,22,True,0,0,155
6,6,1446800938,2124,1972,0,3,63,4,22,True,0,0,151
7,7,1446804030,2328,2046,0,0,63,255,22,True,0,0,138
8,8,1446819063,2002,0,1982,63,0,4,22,False,0,0,182
9,9,1446837251,2961,0,1972,63,0,85,22,False,0,0,133
10,10,1446839926,1562,1983,262,51,63,143,22,True,0,0,133
11,11,1446850598,3280,0,1974,63,0,76,22,False,0,0,122
12,12,1446853394,3995,0,1796,59,0,3,22,False,0,0,138
13,13,1446855028,2452,1956,6,3,63,120,22,True,0,0,123
14,14,1446855096,1728,2047,256,48,63,27,22,True,0,0,182
15,15,1446858132,3122,0,1540,19,0,101,22,False,0,0,121
16,16,1446860653,3318,0,1312,60,0,252,22,False,0,0,121
17,17,1446861016,3798,1543,0,0,3,4,22,True,0,2,123
18,18,1446862325,2820,4,1572,63,3,168,22,False,0,1,133
19,19,1446870404,2234,1974,0,0,63,112,22,True,0,0,184
20,20,1446874022,2284,1974,0,0,63,208,22,True,0,0,112
21,21,1446876812,2019,1974,0,2,63,49,22,True,0,0,111
22,22,1446887066,2754,1852,256,48,63,4,22,True,0,0,191
23,23,1446890850,2742,1958,0,0,63,4,22,True,0,0,132
24,24,1446892093,2986,0,1956,63,0,79,22,False,0,0,132
25,25,1446893288,2430,1974,0,0,63,5,22,True,0,0,153
26,26,1446894280,1499,2046,0,0,63,108,22,True,0,0,191
27,27,1446896551,2116,0,1846,63,0,111,22,False,0,0,192
28,28,1446899255,2201,2047,0,0,63,9,22,True,0,0,138
29,29,1446910512,3388,4,1796,63,51,80,22,False,0,0,155
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,49970,1447828823,3013,1588,0,48,15,98,22,True,0,0,121
49971,49971,1447828834,1356,1983,256,48,63,9,22,True,0,0,123
49972,49972,1447828842,2988,1796,0,32,63,173,22,True,0,0,123
49973,49973,1447828839,2371,1828,0,0,63,3,22,True,0,0,151
49974,49974,1447828847,2937,260,1798,63,51,363,22,False,0,0,152
49975,49975,1447828854,2153,0,2047,63,0,6,22,False,0,0,171
49976,49976,1447828908,1433,6,2047,63,3,104,22,False,0,0,132
49977,49977,1447828968,2542,1982,0,0,63,117,22,True,0,0,154
49978,49978,1447828970,2391,2046,0,0,63,89,22,True,0,0,123
49979,49979,1447829031,2298,390,1846,63,51,204,22,False,0,0,153
49980,49980,1447829030,1374,2047,0,0,63,85,22,True,0,0,122
49981,49981,1447829049,4558,0,1830,63,0,151,22,False,0,0,204
49982,49982,1447829043,3099,0,1846,63,0,8,22,False,0,0,112
49983,49983,1447829039,1831,1982,384,48,63,0,22,True,0,0,121
49984,49984,1447829056,2051,1982,256,48,63,15,22,True,0,0,121
49985,49985,1447829075,1942,0,2044,63,0,3,22,False,0,0,156
49986,49986,1447829058,2917,1972,0,16,63,71,22,True,0,0,138
49987,49987,1447829087,3130,1975,0,0,63,6,22,True,0,0,123
49988,49988,1447829126,2124,4,1972,63,3,142,22,False,0,0,191
49989,49989,1447829126,1556,4,2046,63,3,223,22,False,0,0,121
49990,49990,1447829137,3580,1972,0,0,63,5,22,True,0,0,111
49991,49991,1447829136,2883,1828,0,0,63,62,22,True,0,0,123
49992,49992,1447829133,3159,384,1796,63,48,6,22,False,0,0,156
49993,49993,1447829156,2410,0,1982,63,0,0,22,False,0,0,154
49994,49994,1447829171,2620,0,1846,63,0,215,22,False,0,0,155
49995,49995,1447829192,3025,1824,0,0,63,117,22,True,0,0,111
49996,49996,1447829181,1451,1982,384,48,63,147,22,True,0,0,204
49997,49997,1447829197,2672,1830,0,0,63,130,22,True,0,0,111
49998,49998,1447829189,2211,1982,4,3,63,645,22,True,0,0,151
49999,49999,1447829215,2788,0,2046,63,0,326,22,False,0,0,154

In [36]:
cols

['match_id', 'hero_id', 'player_slot', 'radiant_win']

In [61]:
#organize dataframe such that each match_id is a unique row, and 
#the attributes are 'radiant_team', 'dire_team', and 'radiant_win'
# the '*_team' is a vector of size 112 (112 heroes total) with a value of 1 if that hero was selected
cols = ['match_id', 'hero_id', 'player_slot']
train_data = pd.merge(players[cols], matches.reset_index(), how='left')
train_data = train_data[['match_id','hero_id','radiant_win']]
train_data = train_data.head(50)

In [67]:
train_data.groupby('radiant_win').size()

radiant_win
False    30
True     20
dtype: int64

In [111]:
def unstack_simplify(df):
    return df.unstack().iloc[10:].iloc[:11].reset_index(drop=True)

def make_radiant(df):
    vec = [0]*112
    rad_cols = [0,1,2,3,4]
    return df[rad_cols]

def make_dire(df):
    vec = [0]*112
    dire_cols = [5,6,7,8,9]
    return df[dire_cols]
    
#make binary vector for hero composition
def make_vec(df):
    print df.apply(make_dire)

In [110]:
train_data_comp = train_data.groupby('match_id').apply(unstack_simplify)
make_vec(train_data_comp)

          0   1   2   3   4   5   6   7   8   9   10
match_id
5        NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
6        NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
7        NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
8        NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
9        NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN

In [6]:
matches

,start_time,duration,tower_status_radiant,tower_status_dire,barracks_status_dire,barracks_status_radiant,first_blood_time,game_mode,radiant_win,negative_votes,positive_votes,cluster
match_id,,,,,,,,,,,,
0,1446750112,2375,1982,4,3,63,1,22,True,0,1,155
1,1446753078,2582,0,1846,63,0,221,22,False,0,2,154
2,1446764586,2716,256,1972,63,48,190,22,False,0,0,132
3,1446765723,3085,4,1924,51,3,40,22,False,0,0,191
4,1446796385,1887,2047,0,0,63,58,22,True,0,0,156
5,1446798766,1574,2047,4,3,63,113,22,True,0,0,155
6,1446800938,2124,1972,0,3,63,4,22,True,0,0,151
7,1446804030,2328,2046,0,0,63,255,22,True,0,0,138
8,1446819063,2002,0,1982,63,0,4,22,False,0,0,182
9,1446837251,2961,0,1972,63,0,85,22,False,0,0,133
10,1446839926,1562,1983,262,51,63,143,22,True,0,0,133
11,1446850598,3280,0,1974,63,0,76,22,False,0,0,122
12,1446853394,3995,0,1796,59,0,3,22,False,0,0,138
13,1446855028,2452,1956,6,3,63,120,22,True,0,0,123
14,1446855096,1728,2047,256,48,63,27,22,True,0,0,182
15,1446858132,3122,0,1540,19,0,101,22,False,0,0,121
16,1446860653,3318,0,1312,60,0,252,22,False,0,0,121
17,1446861016,3798,1543,0,0,3,4,22,True,0,2,123
18,1446862325,2820,4,1572,63,3,168,22,False,0,1,133
19,1446870404,2234,1974,0,0,63,112,22,True,0,0,184
20,1446874022,2284,1974,0,0,63,208,22,True,0,0,112
21,1446876812,2019,1974,0,2,63,49,22,True,0,0,111
22,1446887066,2754,1852,256,48,63,4,22,True,0,0,191
23,1446890850,2742,1958,0,0,63,4,22,True,0,0,132
24,1446892093,2986,0,1956,63,0,79,22,False,0,0,132
25,1446893288,2430,1974,0,0,63,5,22,True,0,0,153
26,1446894280,1499,2046,0,0,63,108,22,True,0,0,191
27,1446896551,2116,0,1846,63,0,111,22,False,0,0,192
28,1446899255,2201,2047,0,0,63,9,22,True,0,0,138
29,1446910512,3388,4,1796,63,51,80,22,False,0,0,155
...,...,...,...,...,...,...,...,...,...,...,...,...
49970,1447828823,3013,1588,0,48,15,98,22,True,0,0,121
49971,1447828834,1356,1983,256,48,63,9,22,True,0,0,123
49972,1447828842,2988,1796,0,32,63,173,22,True,0,0,123
49973,1447828839,2371,1828,0,0,63,3,22,True,0,0,151
49974,1447828847,2937,260,1798,63,51,363,22,False,0,0,152
49975,1447828854,2153,0,2047,63,0,6,22,False,0,0,171
49976,1447828908,1433,6,2047,63,3,104,22,False,0,0,132
49977,1447828968,2542,1982,0,0,63,117,22,True,0,0,154
49978,1447828970,2391,2046,0,0,63,89,22,True,0,0,123
49979,1447829031,2298,390,1846,63,51,204,22,False,0,0,153
49980,1447829030,1374,2047,0,0,63,85,22,True,0,0,122
49981,1447829049,4558,0,1830,63,0,151,22,False,0,0,204
49982,1447829043,3099,0,1846,63,0,8,22,False,0,0,112
49983,1447829039,1831,1982,384,48,63,0,22,True,0,0,121
49984,1447829056,2051,1982,256,48,63,15,22,True,0,0,121
49985,1447829075,1942,0,2044,63,0,3,22,False,0,0,156
49986,1447829058,2917,1972,0,16,63,71,22,True,0,0,138
49987,1447829087,3130,1975,0,0,63,6,22,True,0,0,123
49988,1447829126,2124,4,1972,63,3,142,22,False,0,0,191
49989,1447829126,1556,4,2046,63,3,223,22,False,0,0,121
49990,1447829137,3580,1972,0,0,63,5,22,True,0,0,111
49991,1447829136,2883,1828,0,0,63,62,22,True,0,0,123
49992,1447829133,3159,384,1796,63,48,6,22,False,0,0,156
49993,1447829156,2410,0,1982,63,0,0,22,False,0,0,154
49994,1447829171,2620,0,1846,63,0,215,22,False,0,0,155
49995,1447829192,3025,1824,0,0,63,117,22,True,0,0,111
49996,1447829181,1451,1982,384,48,63,147,22,True,0,0,204
49997,1447829197,2672,1830,0,0,63,130,22,True,0,0,111
49998,1447829189,2211,1982,4,3,63,645,22,True,0,0,151
49999,1447829215,2788,0,2046,63,0,326,22,False,0,0,154